package model

import (
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

// Event represents a Flux event with standardized envelope and opaque payload.
// The envelope provides metadata for routing, ordering, and replay.
// The payload is domain-specific and opaque to Flux.
type Event struct {
	// EventID is a UUIDv7 identifier (time-ordered, globally unique).
	// Generated by Flux if not provided by producer.
	EventID string `json:"eventId"`

	// Stream is the logical stream/namespace (maps to NATS subject).
	// Required. Format: lowercase with dots (e.g., "alarms.events", "sensor.hvac.temperature")
	Stream string `json:"stream"`

	// Source identifies the producer system.
	// Required. Examples: "ignition.gateway.prod", "plant-a.scada"
	Source string `json:"source"`

	// Timestamp is the event time in Unix epoch milliseconds (producer time).
	// Required. Used for time-based replay and ordering.
	Timestamp int64 `json:"timestamp"`

	// Key is an optional ordering/partition key for consumer-side grouping.
	// Examples: asset ID, tag path, symbol, device serial
	Key string `json:"key,omitempty"`

	// Schema is optional metadata indicating payload structure and version.
	// Not validated by Flux. Examples: "alarm.raise.v1", "sensor.reading.v2"
	Schema string `json:"schema,omitempty"`

	// Payload is the domain-specific event data (opaque to Flux).
	// Required. Must be a valid JSON object.
	Payload json.RawMessage `json:"payload"`
}

// GenerateEventID creates a new UUIDv7 for the event.
// UUIDv7 is time-ordered, making it efficient for indexing and replay.
func GenerateEventID() string {
	return uuid.Must(uuid.NewV7()).String()
}

// SetTimestampNow sets the event timestamp to the current time.
func (e *Event) SetTimestampNow() {
	e.Timestamp = time.Now().UnixMilli()
}

// GetTimestamp returns the event timestamp as a time.Time.
func (e *Event) GetTimestamp() time.Time {
	return time.UnixMilli(e.Timestamp)
}
